api = "0.7"

[buildpack]
  homepage = "https://github.com/initializ-buildpacks/node-engine"
  id = "initializ-buildpacks/node-engine"
  name = "Initializ Buildpack for Node Engine"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/node-engine/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/optimize-memory", "bin/inspector", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "20.*.*"

  [[metadata.dependencies]]
    checksum = "sha256:b6c60e1e106ad7d8881e83945a5208c1b1d1b63e6901c04b9dafa607aff3a154"
    cpe = "cpe:2.3:a:nodejs:node.js:16.20.1:*:*:*:*:*:*:*"
    deprecation_date = "2023-09-11T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ICU", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v16.20.1?checksum=b6c60e1e106ad7d8881e83945a5208c1b1d1b63e6901c04b9dafa607aff3a154&download_url=https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz"
    source-checksum = "sha256:b6c60e1e106ad7d8881e83945a5208c1b1d1b63e6901c04b9dafa607aff3a154"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz"
    version = "16.20.1"

  [[metadata.dependencies]]
    checksum = "sha256:874463523f26ed528634580247f403d200ba17a31adf2de98a7b124c6eb33d87"
    cpe = "cpe:2.3:a:nodejs:node.js:16.20.2:*:*:*:*:*:*:*"
    deprecation_date = "2023-09-11T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ICU", "MIT", "MIT-0", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v16.20.2?checksum=874463523f26ed528634580247f403d200ba17a31adf2de98a7b124c6eb33d87&download_url=https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz"
    source-checksum = "sha256:874463523f26ed528634580247f403d200ba17a31adf2de98a7b124c6eb33d87"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz"
    version = "16.20.2"

  [[metadata.dependencies]]
    checksum = "sha256:1d08285abd9fad971af5c73d13e8f2a6ae9f2906ee036095dad7d5c286642a4e"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.1:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v18.20.1?checksum=1d08285abd9fad971af5c73d13e8f2a6ae9f2906ee036095dad7d5c286642a4e&download_url=https://nodejs.org/dist/v18.20.1/node-v18.20.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.1/node-v18.20.1-linux-x64.tar.xz"
    source-checksum = "sha256:1d08285abd9fad971af5c73d13e8f2a6ae9f2906ee036095dad7d5c286642a4e"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.1/node-v18.20.1-linux-x64.tar.xz"
    version = "18.20.1"

  [[metadata.dependencies]]
    checksum = "sha256:d0584a21d83d710f947b210434449f6d2a65d14975d6fe9aaf430aae79dc312b"
    cpe = "cpe:2.3:a:nodejs:node.js:18.20.2:*:*:*:*:*:*:*"
    deprecation_date = "2025-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v18.20.2?checksum=d0584a21d83d710f947b210434449f6d2a65d14975d6fe9aaf430aae79dc312b&download_url=https://nodejs.org/dist/v18.20.2/node-v18.20.2-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v18.20.2/node-v18.20.2-linux-x64.tar.xz"
    source-checksum = "sha256:d0584a21d83d710f947b210434449f6d2a65d14975d6fe9aaf430aae79dc312b"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v18.20.2/node-v18.20.2-linux-x64.tar.xz"
    version = "18.20.2"

  [[metadata.dependencies]]
    checksum = "sha256:b8ecd95eebda5882bb70c1088595d87a1fd69cc4be81c317191f4f5ebb34b7ac"
    cpe = "cpe:2.3:a:nodejs:node.js:19.8.1:*:*:*:*:*:*:*"
    deprecation_date = "2023-06-01T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v19.8.1?checksum=b8ecd95eebda5882bb70c1088595d87a1fd69cc4be81c317191f4f5ebb34b7ac&download_url=https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.xz"
    source-checksum = "sha256:b8ecd95eebda5882bb70c1088595d87a1fd69cc4be81c317191f4f5ebb34b7ac"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v19.8.1/node-v19.8.1-linux-x64.tar.xz"
    version = "19.8.1"

  [[metadata.dependencies]]
    checksum = "sha256:e8ea737ee15a62c8752159d12765ed757b5d4b18036b1011d9e4c9e692a4e58d"
    cpe = "cpe:2.3:a:nodejs:node.js:19.9.0:*:*:*:*:*:*:*"
    deprecation_date = "2023-06-01T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v19.9.0?checksum=e8ea737ee15a62c8752159d12765ed757b5d4b18036b1011d9e4c9e692a4e58d&download_url=https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz"
    source-checksum = "sha256:e8ea737ee15a62c8752159d12765ed757b5d4b18036b1011d9e4c9e692a4e58d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v19.9.0/node-v19.9.0-linux-x64.tar.xz"
    version = "19.9.0"


  [[metadata.dependencies]]
    checksum = "sha256:042844eeea4e19fa46687cc028dd5e323602d81784a9da8386c24463e3984e11"
    cpe = "cpe:2.3:a:nodejs:node.js:20.12.1:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v20.12.1?checksum=042844eeea4e19fa46687cc028dd5e323602d81784a9da8386c24463e3984e11&download_url=https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-x64.tar.xz"
    source-checksum = "sha256:042844eeea4e19fa46687cc028dd5e323602d81784a9da8386c24463e3984e11"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-x64.tar.xz"
    version = "20.12.1"


  [[metadata.dependencies]]
    checksum = "sha256:595272130310cbe12301430756f23d153f7ab95d00174c02adc11a2e3703d183"
    cpe = "cpe:2.3:a:nodejs:node.js:20.12.2:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v20.12.2?checksum=595272130310cbe12301430756f23d153f7ab95d00174c02adc11a2e3703d183&download_url=https://nodejs.org/dist/v20.12.2/node-v20.12.2-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v20.12.2/node-v20.12.2-linux-x64.tar.xz"
    source-checksum = "sha256:595272130310cbe12301430756f23d153f7ab95d00174c02adc11a2e3703d183"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.12.2/node-v20.12.2-linux-x64.tar.xz"
    version = "20.12.2"

  [[metadata.dependency-constraints]]
    constraint = "16.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "18.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "19.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "20.*"
    id = "node"
    patches = 2

[[stacks]]
  id = "*"
